export default [
    {
        index:1,
        title:'[置顶]代码搬运工的编程之路',
        date:'2019-06-08',
        path:'/detail/3',
        summary:'为我的努力留下一点痕迹',
    },
    {
        index:2,
        title:'react小白入坑',
        date:'2019-06-08',
        path:'/detail/4',
        summary:'记录学习react的一些事情',
    },
    {
        index:3,
        title:'阿里云服务器之旅',
        date:'2019-06-14',
        path:'/detail/5',
        summary:'记录学习react的一些事情',
    },
    {
        index:4,
        title:'微信小程序与公众号',
        date:'2019-06-14',
        path:'/detail/6',
        summary:'记录学习react的一些事情',
    },
    {
        index:4,
        title:'git git git',
        date:'2019-06-129',
        path:'/detail/7',
        summary:'记录学习react的一些事情',
    },
]